name: mongo_dart
version: 0.4.0
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ted Sander <ted@tedsander.com>
- Paul Evans <pevans@sonardesign.com>
- Stéphane Este-Gracias <sestegra@gmail.com>
- Joel Trottier-Hebert <iamquebecois@gmail.com>
- Tobe O <thosakwe@gmail.com>
- Alexey Danilevsky <alexey.danilevsky@gmail.com>
description: MongoDB driver for Dart
homepage: https://github.com/mongo-dart/mongo_dart
environment:
  sdk: '>=2.0.0-dev.69.3 <3.0.0'
dependencies:
  bson: ^1.0.2
  crypto: '^3.0.0'
  logging: ^1.0.1
  mongo_dart_query: ^1.0.1
  collection: '^1.15.0'
  path: '^1.8.0'
  pool: ^1.5.0
  uuid: ^3.0.2
dev_dependencies:
  test: ^1.16.8
